[package]
name = "ghc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = [
  "cargo",
  "derive",
  "env",
  "string",
  "unicode",
  "wrap_help",
] }
pretty_assertions = "1.4.1"
