AllCops:
  TargetRubyVersion: 3.3.6
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Style/RegexpLiteral:
  EnforcedStyle: percent_r
